/*
 Generated by typeshare 1.13.4
*/

export interface Book {
    title: string;
    author: string;
    md5: string;
    imgUrl: string;
    size: string;
    genre: string;
    format: string;
    year?: string;
    imgFallbackColor: string;
}

export interface SearchResponse {
    totalPages: number;
    books: Book[];
}

export interface StartTransferResponse {
    short_code: string;
    created_at: string;
}
